---
# cluster = groupe de noeuds, plus large qu'une file d'attente (queue)
# c8220 match c8220lin130 et c8220node201
# ou par hostname (quelques cas particuliers):
# r820node253 match r820node253
#cluster_name:
#  first part of hostnames
Epyc:
  c6525
Lake:
  c6420
  xlr170
  xlr178
  r730gpu
  r740gpu
  r740bigmem201
E5:
# les changement de nom en cours de vie, Ã§a va pas aider...
  sl230
  c82gpgpu
  c8220
  c6320
  r720gpu
  r720gpgpu
  r820node253
  celera
  r730gpgpu
X5:
  sl390
  r815
  c6100
  r422
default:
# +catchall pour ce qui ne matche rien (UNKNOWN)
  dl165
  dl175
  r410
  x41z
  v20z
  v22z
  v40z
  m600

